name: shampoo

channels:
    - astropy
    - salilab

dependencies:
    - astropy
    - h5py
    - matplotlib
    - numpy
    - scikit-image
    - scikit-learn
    - fftw
    - pip:
        - mst_clustering
        - pyfftw
